# Generated by Django 4.2.11 on 2024-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.TextField(max_length=300)),
                ('img_desc', models.TextField(max_length=300)),
            ],
        ),
    ]
